### ISSUE TITLE
Does not work in .NET Framework | System.TypeLoadException

### ISSUE THREAD

**Issue by DestroyerDarkNess** [SupinePandora43/UltralightNet#79]
**Note:** Tested on .NET Core 6.0 Worked fine. The problem is in the .NET Framework.  

I suspect it's the way you wrote the structure:

![image](https://github.com/SupinePandora43/UltralightNet/assets/32405118/b36931a3-7468-4a35-9322-a8545691b776)

**Steps to Reproduce:**

1) Create a console project in the .NET Framework 4.8.
2) set the project to x64.
3) Install the nuget packages.
4) Extract the SDK Ultralight 1.3.0 libraries to the project path.
5) Run the example: [https://github.com/SupinePandora43/UltralightNet/blob/master/Examples/AppCore/UltralightNet.AppCore.TestApp/Program.cs](UltralightNet.AppCore.TestApp)

**Error:**

![image](https://github.com/SupinePandora43/UltralightNet/assets/32405118/e0b39785-c4ad-42dd-b135-ca6c5bf92edc)

> System.TypeLoadException: 'Cannot marshal field 'FileExists' of type 'UltralightNet.Platform.HighPerformance.ULFileSystem': There is no marshalling support for this type.'

**_If I am doing something wrong, please point me out._**

**Comment by SupinePandora43** [comment]
I've already fixed it more than [8 months ago](https://github.com/SupinePandora43/UltralightNet/commit/0a55ae9fa3d6a95e0fb4b9287a2e856ae536f1dd). Though, as many other fixes/changes, it didn't get to nuget because I've not published it.
I'll see what I can do, but for now, I can only recommend you to use UltralightNet directly from the `develop` branch.
Please reply if something doesn't work, if you need help with getting UltralightNet to build locally, I recommend you to use [the official Ultralight discord server](https://discord.gg/25qHwap) with the `#c-sharp` channel for communication.

**Comment by DestroyerDarkNess** [comment]
I guess it was a type problem. I see you solved it, I'll try to build the develop branch. Thanks for answering.
